In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        # 1.0除以每個element，取倒數，並把數值copy到empty(output) array中
        output[i] = 1.0 / values[i]
    return output

# 生成一個array
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

`%timeit`: 測量運行時間。

In [4]:
big_arr = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_arr)

1.34 s ± 96.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# UFuncs (Universal Function)

In [5]:
# Call function(用for迴圈)
print(compute_reciprocals(values))
# Ufunsc
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


※ 結果是一樣的

In [6]:
%timeit (1.0 / big_arr)

1.83 ms ± 88.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


執行時間從1.18s -> **1.66ms** (縮短非常多)

In [7]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [8]:
arr = np.arange(9).reshape(3, 3)
# 對所有element進行2**ele運算
2 ** arr

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [9]:
arr - 10

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [10]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [11]:
# 可以對array的所有元素進行相同運算
print(f"array = {arr}")
print(f"array + 5 = {arr + 5}")
print(f"array - 5 = {arr - 5}")
print(f"array * 2 = {arr * 2}")
print(f"array / 2 = {arr / 2}")
print(f"array // 2 = {arr // 2}")
print(f"array % 2 = {arr % 2}")

array = [0 1 2 3 4]
array + 5 = [5 6 7 8 9]
array - 5 = [-5 -4 -3 -2 -1]
array * 2 = [0 2 4 6 8]
array / 2 = [0.  0.5 1.  1.5 2. ]
array // 2 = [0 0 1 1 2]
array % 2 = [0 1 0 1 0]


In [12]:
# 也可以結合起來一次運算
-(0.5 * arr + 10) ** 2

array([-100.  , -110.25, -121.  , -132.25, -144.  ])

Ufuncs也支援Python原生functions

In [13]:
# abs
arr = np.array(
    [-5, -4, -100, 0, 9]
)
abs(arr)

array([  5,   4, 100,   0,   9])

In [14]:
# NumPy function
np.absolute(arr)

array([  5,   4, 100,   0,   9])

In [15]:
# Or np.abs
np.abs(arr)

array([  5,   4, 100,   0,   9])

In [16]:
# Complex Data
arr = np.array(
    [3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j]
)
np.abs(arr)

array([5., 5., 2., 1.])

※ |a + bi| = 取平方根(a^2 + b^2)

## Trigonometric Functions
三角函式

In [17]:
arr = np.linspace(0, np.pi, 3)
arr

array([0.        , 1.57079633, 3.14159265])

In [18]:
print(f"array: {arr}")
print(f"sin(arr): {np.sin(arr)}")
print(f"cos(arr): {np.cos(arr)}")
print(f"tan(arr): {np.tan(arr)}")

array: [0.         1.57079633 3.14159265]
sin(arr): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(arr): [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(arr): [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Inverse Trigonometric

In [19]:
arr = [-1, 0, 1]
print(f"arr: {arr}")
print(f"arcsin(x): {np.arcsin(arr)}")
print(f"arccos(x): {np.arccos(arr)}")
print(f"arctan(x): {np.arctan(arr)}")

arr: [-1, 0, 1]
arcsin(x): [-1.57079633  0.          1.57079633]
arccos(x): [3.14159265 1.57079633 0.        ]
arctan(x): [-0.78539816  0.          0.78539816]


## Exponents & Logarithms
指數 & 對數

In [20]:
arr = [1, 2, 3]
arr

[1, 2, 3]

In [21]:
print(f"e ^ arr: {np.exp(arr)}")
print(f"2 ^ arr: {np.exp2(arr)}")
print(f"3 ^ arr: {np.power(4, arr)}")

e ^ arr: [ 2.71828183  7.3890561  20.08553692]
2 ^ arr: [2. 4. 8.]
3 ^ arr: [ 4 16 64]


In [22]:
arr = [1, 2, 3, 4, 5]
print(arr)
print(f"ln(x): {np.log(arr)}")
print(f"log2(x): {np.log2(arr)}")
print(f"log10(x): {np.log10(arr)}")

[1, 2, 3, 4, 5]
ln(x): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log2(x): [0.         1.         1.5849625  2.         2.32192809]
log10(x): [0.         0.30103    0.47712125 0.60205999 0.69897   ]


數據平滑處理: `expm1(x)` & `log1p(x)`

In [29]:
arr = [0.1, 0.01, 0.001, 0.0001]
print(arr)
print(f"exp(x) - 1: {np.expm1(arr)}")
print(f"log(1 + x): {np.log1p(arr)}")

[0.1, 0.01, 0.001, 0.0001]
exp(x) - 1: [1.05170918e-01 1.00501671e-02 1.00050017e-03 1.00005000e-04]
log(1 + x): [9.53101798e-02 9.95033085e-03 9.99500333e-04 9.99950003e-05]


LCM & GCD (最小公倍數 & 最大公因數)

Reference: https://www.w3schools.com/python/numpy/numpy_ufunc_lcm.asp

In [23]:
# 找出2數之間的LCM
num1 = 4
num2 = 5
print(np.lcm(num1, num2))

20


In [24]:
# 找出多個數值間的LCD
nums = [3, 5, 7]
print(np.lcm.reduce(nums))

105


In [25]:
num1 = 12
num2 = 6
print(np.gcd(num1, num2))

6


In [26]:
nums = [12, 4, 6]
print(np.gcd.reduce(nums))

2


Sets(集合) In NumPy

In [27]:
arr = np.array(
    [1, 10, 2, 3, 5, 5, 1, 7, 3]
)
# 與Pandas drop_duplicate()一樣可達到相同目的
print(np.unique(arr))

[ 1  2  3  5  7 10]


`union1d`: 找出2個array之間唯一的值(僅出現1次)

In [28]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([2, 3, 5, 7, 11])

print(np.union1d(arr1, arr2))

[ 1  2  3  5  7  9 11]
